apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: medconnect
  labels:
    app.kubernetes.io/name: medconnect
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DB_USER: medconnect
  DB_PASSWORD: medconnect
  JWT_SECRET: bWVkY29ubmVjdC1rOHMtand0LXNlY3JldC0zMi1ieXRlcyEh
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  AI_API_KEY: ""
